"""init

Revision ID: 34e472d43444
Revises: 980532456c5f
Create Date: 2026-05-28 17:40:36.352167

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "34e472d43444"
down_revision: str | Sequence[str] | None = "980532456c5f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "addresses",
        sa.Column("line1", sa.String(length=100), nullable=True),
        sa.Column("city", sa.Integer(), nullable=True),
        sa.Column("postal_code", sa.String(length=255), nullable=True),
        sa.Column("country", sa.String(length=255), nullable=True),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["employee_id"], ["employees.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_addresses_employee_id"), "addresses", ["employee_id"], unique=False
    )
    op.create_index(op.f("ix_addresses_id"), "addresses", ["id"], unique=False)
    op.drop_index(op.f("ix_address_employee_id"), table_name="address")
    op.drop_index(op.f("ix_address_id"), table_name="address")
    op.drop_table("address")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "address",
        sa.Column("line1", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        sa.Column("city", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "postal_code", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column(
            "country", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "deleted_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("employee_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
            name=op.f("address_employee_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("address_pkey")),
    )
    op.create_index(op.f("ix_address_id"), "address", ["id"], unique=False)
    op.create_index(
        op.f("ix_address_employee_id"), "address", ["employee_id"], unique=False
    )
    op.drop_index(op.f("ix_addresses_id"), table_name="addresses")
    op.drop_index(op.f("ix_addresses_employee_id"), table_name="addresses")
    op.drop_table("addresses")
    # ### end Alembic commands ###
