"""password added

Revision ID: 3cf8d3272b8b
Revises: d23e58df22ad
Create Date: 2026-05-29 16:04:59.878558

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3cf8d3272b8b"
down_revision: str | Sequence[str] | None = "d23e58df22ad"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "employees", sa.Column("password_hash", sa.String(length=255), nullable=True)
    )
    op.execute(
        "UPDATE employees SET password_hash = 'placeholder' WHERE password_hash is NULL"
    )
    op.alter_column("employees", "password_hash", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("employees", "password_hash")
    # ### end Alembic commands ###
