"""init

Revision ID: 980532456c5f
Revises: 246ca8c0110f
Create Date: 2026-05-28 17:30:23.778359

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "980532456c5f"
down_revision: str | Sequence[str] | None = "246ca8c0110f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("address", sa.Column("employee_id", sa.Integer(), nullable=False))
    op.create_index(
        op.f("ix_address_employee_id"), "address", ["employee_id"], unique=False
    )
    op.create_foreign_key(
        None, "address", "employees", ["employee_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "address", type_="foreignkey")
    op.drop_index(op.f("ix_address_employee_id"), table_name="address")
    op.drop_column("address", "employee_id")
    # ### end Alembic commands ###
