"""init

Revision ID: a13a08edbaba
Revises: e48680df8e7a
Create Date: 2026-05-28 20:38:29.592291

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "a13a08edbaba"
down_revision: str | Sequence[str] | None = "e48680df8e7a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
