"""init

Revision ID: af34ddf4d6b2
Revises:
Create Date: 2026-05-28 17:02:41.956317

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "af34ddf4d6b2"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("employees", sa.Column("age", sa.Integer(), nullable=True))
    op.add_column(
        "employees", sa.Column("address", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("employees", "address")
    op.drop_column("employees", "age")
    # ### end Alembic commands ###
