"""fix some errors

Revision ID: d48f4d751bcb
Revises: c6c3de2137a7
Create Date: 2026-05-31 08:41:17.809726

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "d48f4d751bcb"
down_revision: Union[str, Sequence[str], None] = "c6c3de2137a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
