"""fix some errors

Revision ID: d48f4d751bcb
Revises: c6c3de2137a7
Create Date: 2026-05-31 08:41:17.809726

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "d48f4d751bcb"
down_revision: str | Sequence[str] | None = "c6c3de2137a7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
